"""add_order_shipping_and_details

Revision ID: 019c5bb7d3c1
Revises: e893df31b848
Create Date: 2025-12-08 14:49:43.343392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019c5bb7d3c1'
down_revision: Union[str, None] = 'e893df31b848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('product_image', sa.String(length=500), nullable=True))
    op.add_column('order_items', sa.Column('product_size', sa.String(length=20), nullable=True))
    op.add_column('order_items', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('shipping_name', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('shipping_email', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('shipping_fee', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_email')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_name')
    op.drop_column('order_items', 'total_price')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'product_size')
    op.drop_column('order_items', 'product_image')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
