"""add stock to product table

Revision ID: 6a4d266ee151
Revises: 06c4bad6062f
Create Date: 2025-12-09 15:52:03.055819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4d266ee151'
down_revision: Union[str, None] = '06c4bad6062f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True, default=0))
    # Update existing rows
    op.execute("UPDATE products SET stock = 0 WHERE stock IS NULL")
    # Make it not null
    op.alter_column('products', 'stock', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
