"""Add order_id, images, video to reviews

Revision ID: d82e34d21848
Revises: 386eacf9194d
Create Date: 2025-12-13 01:47:53.245545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82e34d21848'
down_revision: Union[str, None] = '386eacf9194d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('video', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'video')
    op.drop_column('reviews', 'images')
    op.drop_column('reviews', 'order_id')
    # ### end Alembic commands ###
